# Generated by Django 5.1.3 on 2024-11-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TigerTutorsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='', editable=False, error_messages={'unique': 'Username already exists', 'wrong': 'Wrong password'}, help_text='Required. 8 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(default='', editable=False, error_messages={'unique': 'Username already exists', 'wrong': 'Wrong password'}, help_text='Required. 8 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=8, unique=True)),
            ],
        ),
    ]
