# Generated by Django 5.1.3 on 2024-11-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TigerTutorsApp', '0003_computerdocument_mathematicsdocument_physicsdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathematicsDocument',
            new_name='Documents',
        ),
        migrations.DeleteModel(
            name='ComputerDocument',
        ),
        migrations.DeleteModel(
            name='PhysicsDocument',
        ),
    ]
