# Generated by Django 5.1.3 on 2024-12-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TigerTutorsApp', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
