# Generated by Django 5.1.3 on 2024-12-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TigerTutorsApp', '0009_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
